# Generated by Django 4.2.1 on 2023-07-15 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sender',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='sent_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
